config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'terrains#index'
  resources :terrains
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/terrain.rb
class Terrain < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/terrains_controller.rb
class TerrainsController < ApplicationController
skip_before_action :authenticate_user!, only: [ :index, :show ]
  before_action :set_terrain, only: [:show, :edit, :update, :destroy]

  # GET /terrains
  #def index
    #@terrains = Terrain.all
  #end

  def index
         if params[:query].present?

         @terrains = Terrain.where("lower(title)  LIKE ?", "%" + params[:query].downcase + "%")
         #@terrains = Terrain.where("lower(description)  LIKE ?", "%" + params[:query].downcase + "%")
         #@terrains = Terrain.where("lower(value)  LIKE ?", "%" + params[:query].downcase + "%")
        else

         @terrains = Terrain.order(created_at: :desc)
        end
      end

  # GET /terrains/1
  def show
  end

  # GET /terrains/new
  def new
    @terrain = Terrain.new
  end

  # GET /terrains/1/edit
  def edit
  end

  # POST /terrains
  def create
    @terrain = Terrain.new(terrain_params)
    @terrain.user = current_user
    if @terrain.save
      redirect_to @terrain, notice: 'Terrain was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /terrains/1
  def update
    if @terrain.update(terrain_params)
      redirect_to @terrain, notice: 'Terrain was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /terrains/1
  def destroy
    @terrain.destroy
    redirect_to terrains_url, notice: 'Terrain was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_terrain
      @terrain = Terrain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def terrain_params
      params.require(:terrain).permit(:title, :description, :value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DEVISE</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "react.png" %>
    <% end %>

<nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
         <form class="d-flex" action= "/terrains" method="get">

          <input class="form-control me-2" type="text" name="query" placeholder="title" aria-label="Search">

          <button class="btn btn-outline-success" type="submit">Busqueda</button>

        </form>
      </div>
  </nav>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">

            <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "photo1.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mensajes", "#", class: "dropdown-item" %>
              <%= link_to "Usuarios", "#", class: "dropdown-item" %>
              <%= link_to "Adminitrador", "#", class: "dropdown-item" %>

            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Ingresar sesion", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/terrains/_form.html.erb
<%= simple_form_for(@terrain) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :value %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/terrains/edit.html.erb
<h1>Editing Terrain</h1>

<%= render 'form', terrain: @terrain %>

<%= link_to 'Show', @terrain %> |
<%= link_to 'Back', terrains_path %>

app/views/terrains/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Terrains</h1>
<% if user_signed_in? %>
<%= link_to 'New Terrain', new_terrain_path %>
<% end %>
</div>

<div class="container">
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Value</th>

      <th colspan="3"></th>

    </tr>
  </thead>

  <tbody>
    <% @terrains.each do |terrain| %>
      <tr>
        <td><%= terrain.title %></td>
        <td><%= terrain.description %></td>
        <td><%= terrain.value %></td>

        <td><%= link_to '   Show   ', terrain %></td>
        <% if user_signed_in? %>


        <td><%= link_to '   Edit    ', edit_terrain_path(terrain) %></td>

        <td><%= link_to '  Destroy  ', terrain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Terrain', new_terrain_path %>
<% end %>
</div>

app/views/terrains/new.html.erb
<h1>New Terrain</h1>

<%= render 'form', terrain: @terrain %>

<%= link_to 'Back', terrains_path %>

app/views/terrains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @terrain.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @terrain.description %>
</p>

<p>
  <strong>Value:</strong>
  <%= @terrain.value %>
</p>


<% if user_signed_in? %>
<%= link_to 'Edit', edit_terrain_path(@terrain) %> |
<% end %>
<%= link_to 'Back', terrains_path %>